'use strict';
const fullName = 'Allyson Greven';
console.log('full name:' + ' ' + fullName);
console.log(typeof fullName);
const isCool = true;
console.log('is she cool?' + ' ' + isCool);
console.log(typeof isCool);
const totalPets = 2;
console.log('total # of pets:' + ' ' + totalPets);
console.log(typeof totalPets);
const empty = null;
console.log('the value of empty:' + ' ' + empty);
console.log(typeof empty);
const nothing = undefined;
console.log('the value of nothing:' + ' ' + nothing);
console.log(typeof nothing);
