'use strict';
const width = 12;
const height = 14;
const area = width * height;
console.log('value of area: ' + area);
console.log('typeof area: ' + typeof area);
const bill = 6;
const payment = 12;
const change = payment - bill;
console.log('value of change: ' + change);
console.log('typeof change: ' + change);
const quizzes = 95;
const midterm = 83;
const final = 92;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grades: ' + grade);
console.log('typeof grades: ' + grade);
const firstName = 'Allyson';
const lastName = 'Greven';
const fullName = firstName + ' ' + lastName;
console.log('value of full name: ' + fullName);
console.log('typeof full name: ' + fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log('value of pH: ' + isAcidic);
console.log('typeof isAcidic: ' + isAcidic);
const headCount = 58;
const isSparta = headCount === 300;
console.log('value of isSparta: ' + isSparta);
console.log('typeof isSparta: ' + isSparta);
const motto = fullName + ' ' + 'is the GOAT!';
console.log('value of motto: ' + motto);
console.log('typeof motto: ' + motto);
